repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1 
    hooks:
    - id: flake8
      language_version: python3.7

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

